### ISSUE TITLE
This App doesn't run well.

### ISSUE THREAD

**Issue by dev0614** [dev0614/wagmi-app-connectkit#4]
I hope this message finds you well. I am currently experiencing some challenges with the code in question, and I am seeking your valuable assistance to address the performance issues.

I have identified a problem in the code, which seems to be impacting its functionality negatively. I have posted an issue on GitHub to seek help from the community, and I would greatly appreciate it if you could take a moment to review the code and share any insights you may have.

**Comment by AtlanticTurtle** [comment]
okay. thans for your advice.
